from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_login, name='login'),
    path('signout', views.user_logout, name='sign_out'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher/classes/', views.teacher_classes, name='teacher_classes'),
    path('class/<int:class_id>/mark/', views.mark_attendance, name='mark_attendance'),
    # path('class/<int:class_id>/update_attendance', views.update_past_attendance, name='update_past_attendance'),
    path('class/<int:class_id>/excel-attendance/', views.excel_attendance, name='excel_attendance'),
    path('class/<int:class_id>/attendance/', views.show_attendance, name='show_attendance'),
    path('student/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('student/profile/', views.student_profile, name='student_profile'),
    path('student/edit_profile',views.edit_student_profile,name='edit_profile'),
    path('class/<int:class_id>/bulk-upload/', views.bulk_student_upload, name='bulk_upload'),
    path('change-password/', views.first_login_password_change, name='first_login_password_change'),
    path('fetch_attendance/<int:class_id>/', views.fetch_attendance, name='fetch_attendance'),
    path('class/<int:class_id>/', views.class_detail, name='class_detail'),
    path('otp',views.verify_otp,name='otp'),
    path("sucess",views.sucesssssss,name="sucess"),
    path('generate-attendance', views.export_attendance, name='generate_attendance'),
    path('change_your_password', views.change_password, name='change_pass'),
    path('admin-dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/program',views.programs,name='program'),
    path('admin-dashboard/teachers',views.teachers,name='teachers'),
    path('admin-dashboard/attendance_policy',views.attendance_policy,name='attendance_policy'),
    path("admin-dashboard/add-teacher/", views.add_teacher_view, name="add_teacher"),
    path('admin-dashboard/classes/', views.class_list, name='class_list'),
    path('admin-dashboard/classes/create/', views.create_class, name='create_class'),
     path("attendance/past/", views.select_class, name="select_class"),
    path("attendance/past/<int:class_id>/", views.add_past_attendance, name="add_past_attendance"),
]