# Generated by Django 5.1.5 on 2025-02-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_user_role_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="roll_number",
        ),
    ]
