# Generated by Django 5.1.5 on 2025-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_remove_timetable_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
