# Generated by Django 5.1.5 on 2025-03-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_timetable_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="date",
        ),
    ]
