# Generated by Django 5.1.5 on 2025-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
