# Generated by Django 5.1.5 on 2025-03-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_academicyear_semester_course_timetable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="class_assigned",
        ),
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(
                related_name="courses", to="attendance.teacher"
            ),
        ),
        migrations.CreateModel(
            name="ScheduledClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Topic covered in this session",
                        max_length=255,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_classes",
                        to="attendance.course",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_classes",
                        to="attendance.timetable",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="scheduled_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendance.scheduledclass",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "scheduled_class", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="timetable",
        ),
    ]
